# Generated by Django 2.2.16 on 2020-10-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
